SCALING_FACTOR = 2.5
REFACTORING = True

MOTOR_SPACING_MM = 10.0   # mm per motor index (Y axis)
BOARD_SPACING_MM = 10.0   # mm per board index (X axis)

BOARD_COUNT = 30
MOTORS_PER_BOARD = 14

MIN_LIMITS_FILE = "motor_min.csv"
MAX_LIMITS_FILE = "motor_max.csv"

DEFAULT_MIN_LIMIT = 100
DEFAULT_MAX_LIMIT = 150

FUNCTION_DESCRIPTION = "u(x, y, t)"

DYNAMIC_CYCLE_HZ = 1.0
BLINK_DURATION_SEC = 0.10

UPDATE_HZ = 100.0