#include "board_config.h"

// NOTE: pointers are const (array contents can’t change); the GPIO registers they point to are not const.
GPIO_TypeDef * const dir_ports[16] = {
  GPIOE, GPIOE, GPIOE, GPIOE,
  GPIOE, GPIOB, GPIOB, GPIOB,
  GPIOD, GPIOD, GPIOD, GPIOD,
  GPIOA, GPIOA, GPIOA, GPIOC
};

const uint16_t dir_pins[16] = {
  DIR_1_Pin,  DIR_2_Pin,  DIR_3_Pin,  DIR_4_Pin,
  DIR_5_Pin,  DIR_6_Pin,  DIR_7_Pin,  DIR_8_Pin,
  DIR_9_Pin,  DIR_10_Pin, DIR_11_Pin, DIR_12_Pin,
  DIR_13_Pin, DIR_14_Pin, DIR_15_Pin, DIR_16_Pin
};


// Use the real handles generated by Cube (htim1/3/4/8) from tim.c
TIM_HandleTypeDef * const pwm_timer_handles[16] = {
  &htim1, &htim1, &htim1, &htim1,
  &htim8, &htim8, &htim8, &htim8,
  &htim4, &htim4, &htim4, &htim4,
  &htim3, &htim3, &htim3, &htim3
};

const uint32_t pwm_timer_channels[16] = {
  TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4,
  TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4,
  TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4,
  TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4
};

const uint8_t active_motors[14] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}; 
uint16_t board_id = 0; 
uint32_t current_time_us = 0;
